name: Smarttrip
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.3.0
  flutter_map: ^8.3.1
  latlong2: ^0.9.1
  geolocator: ^14.0.3
  http: ^1.6.0
  dio: ^5.7.0
  image_picker: ^1.1.2
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.1.1
  shared_preferences: ^2.3.5
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.0
  firebase_core: ^3.12.0
  firebase_messaging: ^15.2.4
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # ==========================================================
  # FLUTTER LAUNCHER ICONS
  # ==========================================================

  flutter_launcher_icons: ^0.14.4

# ============================================================
# FLUTTER
# ============================================================

flutter:
  uses-material-design: true

  # ==========================================================
  # ASSETS
  # ==========================================================

  assets:
    - assets/images/
    - assets/icons/


# ============================================================
# FLUTTER LAUNCHER ICONS
# ============================================================

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true

  # Logo aplikasi
  image_path: "assets/images/smarttrip_logo_icon.png"

  # ==========================================================
  # ANDROID ADAPTIVE ICON
  # ==========================================================

  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/smarttrip_logo_icon.png"

  # ==========================================================
  # WEB ICON
  # ==========================================================

  web:
    generate: true
    image_path: "assets/images/smarttrip_logo_icon.png"
    background_color: "#FFFFFF"
    theme_color: "#55B8F4"